name: 'GitHub NuGet Private Source Authorisation'
description: 'Authorises access to a private GitHub NuGet package source, so you can restore packages.'

branding:
  icon: "lock"
  color: "blue"

inputs:
  owner:
    description: "The owner of the NuPkg repository you would like to access, as displayed in their GitHub URL."
    required: false
    default: ${{ github.repository_owner }}
  name:
    description: "The name of the NuPkg source"
    required: false
    default: "Github-${{ github.repository_owner }}"
  token:
    description: "Personal Access Token with permission to read packages."
    required: false

runs:
  
  using: "composite"
  
  steps: 
    - name: Unix
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          "$SHELL" "${{ github.action_path }}\\action.sh"
        else
          "$SHELL" "${{ github.action_path }}/action.sh"
        fi
      env:
        owner: "${{inputs.owner}}"
        name: "${{inputs.name}}"
        token: "${{inputs.token}}"