name: 'GitHub NuGet Private Source Authorisation'
description: 'Authorises access to a private GitHub NuGet package source, so you can restore packages.'

branding:
  icon: "lock"
  color: "blue"

inputs:
  owner:
    description: "The owner of the NuPkg repository you would like to access, as displayed in their GitHub URL."
    required: false
    default: "Owner of the repository the Action is running within."
  name:
    description: "The name of the NuPkg source"
    required: false
    default: "Github-$repository-owner"
  token:
    description: "Personal Access Token with permission to read packages."
    required: true

runs:
  
  using: "composite"
  
  steps: 
    - shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        owner: "${{inputs.owner}}"
        name: "${{inputs.name}}"
        token: "${{inputs.token}}"
