name: 'GitHub NuGet Private Source Authorisation'
description: 'Authorises access to a private GitHub NuGet package source, so you can restore packages.'

branding:
  icon: "lock"
  color: "blue"

inputs:
  owner:
    description: "The owner of the NuPkg repository you would like to access, as displayed in their GitHub URL."
    required: false
    default: ${{ github.repository_owner }}
  name:
    description: "The name of the NuPkg source"
    required: false
    default: "GitHub-${{ github.repository_owner }}"
  token:
    description: "Personal Access Token with permission to read packages."
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        script_path=${{ github.action_path }}
        last_part=${script_path##*/}
        if [[ "$last_part" == "main" ]]; then
          full_path="${script_path%$last_part}"
        fi
        "$script_path/action.sh"
      env:
        owner: "${{inputs.owner}}"
        name: "${{inputs.name}}"
        token: "${{inputs.token}}"
        GITHUB_TOKEN: ${{github.token}}
        DOTNET_NOLOGO: "1"
