name: 'GitHub NuGet Private Source Authorisation'
description: 'Authorises access to a private GitHub NuGet package source, so you can restore packages.'

branding:
  icon: "lock"
  color: "blue"

inputs:
  owner:
    description: "The owner of the NuPkg repository you would like to access, as displayed in their GitHub URL."
    required: true
    default: "${{ github.repository_owner }}"
  name:
    description: "The name of the NuPkg source"
    required: true
    default: "Github-${{ github.repository_owner }}"
  token:
    description: "Personal Access Token with permission to read packages."
    required: true
    default: "${{ github.token }}"

runs:
  
  using: "composite"
  
  steps: 
    - name: Execute action bash script
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          "${{ github.action_path }}\\action.sh"
        else
          "${{ github.action_path }}/action.sh"
        fi
      env:
        owner: "${{ inputs.owner }}"
        name: "${{ inputs.name }}"
        token: "${{ inputs.token }}"
        GITHUB_TOKEN: "${{ github.token }}"
        DOTNET_NOLOGO: "1"
